### ISSUE TITLE
How can I adjust blog width

### ISSUE THREAD

**Issue by jftuga** [caris-events/tunalog#33]
I want to make my blog wider.

I tried editing the global `Content Width` to `wide` and then edited `./system/themes/default/assets/style.css`:

```css
html.container-large .ts-container {
    --width: 980px;
}
```

I recompiled and reran the binary, but the width still seems to be the same.  IIRC, the original width was `810px`.  What else do I need to change?

Thanks.
